@startuml table
!define TRANSACTION CAE7F2
!define MASTER F9DFD5

entity users as "users\nユーザー" <<T,TRANSACTION>> {
  + id INT(10) [PK]
  --
  name VARCHAR(30) [名前]
  # country_id [FK]
  created_at TIMESTAMP
  updated_at TIMESTAMP
}


entity posts as "posts\n記事" <<T,TRANSACTION>> {
  + id INT(10) [PK]
  --
  title VARCHAR(30) [タイトル]
  body VARCHAR(255) [記事]
  # user_id [FK]
  created_at TIMESTAMP
  updated_at TIMESTAMP
}


entity countries as "countries\n国" <<M,MASTER>> {
  + id INT(10) [PK]
  --
  name VARCHAR(50) [国名]
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

@enduml
